name = "ghe-bharari-backend"
main = "src/index.js"
compatibility_date = "2024-11-06"

[[kv_namespaces]]
binding = "MEMBERS_KV"
id = "7e18acf7740b459487811710ba8c8ad2"
preview_id = "your-preview-kv-namespace-id"

[[kv_namespaces]]
binding = "BUSINESSES_KV"
id = "78d2e3bf0c5840b3a048fba8839ffd5d"
preview_id = "your-preview-businesses-kv-namespace-id"

[[kv_namespaces]]
binding = "VIDEOS_KV"
id = "d9172749e8df4eadb9a02d0b6e8ec657"
preview_id = "your-preview-videos-kv-namespace-id"

[vars]
CORS_ORIGIN = "https://ghebhararisevabhavisanstha.org"
